version: '3.8'

services:
  laravel_app:
    image: php:8.1-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - laravel_db
    command: >
      sh -c "apt-get update &&
             apt-get install -y unzip git curl &&
             curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
             php-fpm"

  laravel_db:
    image: mysql:8
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  laravel_nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
    ports:
      - "8000:80"

volumes:
  db_data:

